"""
Report Generator
Generates comprehensive markdown reports from analysis results
"""

from typing import Dict, List
from datetime import datetime
from .disease_risk_analyzer import DiseaseRiskResult, VariantMatch


def generate_reports(
    analysis_result: DiseaseRiskResult,
    subject_name: str = "Subject"
) -> Dict[str, str]:
    """
    Generate all report types from analysis results

    Returns:
        Dictionary with report type -> markdown content
    """
    return {
        "summary": generate_summary_report(analysis_result, subject_name),
        "genetic": generate_genetic_report(analysis_result, subject_name),
        "disease_risk": generate_disease_risk_report(analysis_result, subject_name),
        "protocol": generate_protocol_report(analysis_result, subject_name),
    }


def generate_summary_report(result: DiseaseRiskResult, subject_name: str) -> str:
    """Generate executive summary report"""
    report = f"""# Genetic Analysis Summary

**Subject:** {subject_name}
**Date:** {datetime.now().strftime("%B %d, %Y")}

## Overview

| Metric | Value |
|--------|-------|
| Total Variants Analyzed | {result.total_variants_analyzed:,} |
| ClinVar Database Matches | {result.clinvar_matches:,} |
| High Risk Variants | {len(result.high_risk_variants)} |
| Moderate Risk Variants | {len(result.moderate_risk_variants)} |
| Beneficial Variants | {len(result.beneficial_variants)} |
| Pharmacogenomic Findings | {len(result.pharmacogenomic_variants)} |

## Key Findings

"""

    if result.high_risk_variants:
        report += "### High Priority Items\n\n"
        for variant in result.high_risk_variants[:5]:
            report += f"- **{variant.gene}** ({variant.rsid}): {variant.condition}\n"
        report += "\n"

    if result.pharmacogenomic_variants:
        report += "### Drug Metabolism Variants\n\n"
        for variant in result.pharmacogenomic_variants[:5]:
            report += f"- **{variant.gene}** ({variant.rsid}): {variant.condition}\n"
        report += "\n"

    report += """## Categories Summary

"""
    for category, count in sorted(result.categories.items(), key=lambda x: -x[1]):
        report += f"- **{category}**: {count} findings\n"

    report += """

## Important Disclaimer

This report is for informational purposes only and should not be used as a substitute for professional medical advice, diagnosis, or treatment. Always consult with qualified healthcare providers before making any health decisions based on genetic information.

---
*Generated by GeneHealth Analysis Platform*
"""
    return report


def generate_genetic_report(result: DiseaseRiskResult, subject_name: str) -> str:
    """Generate detailed genetic analysis report"""
    report = f"""# Comprehensive Genetic Analysis Report

**Subject:** {subject_name}
**Analysis Date:** {datetime.now().strftime("%B %d, %Y")}

---

## Analysis Overview

This report provides a detailed analysis of {result.total_variants_analyzed:,} genetic variants identified in your DNA sample. Each variant has been evaluated against clinical databases including ClinVar and curated pharmacogenomic resources.

"""

    # High Risk Variants Section
    if result.high_risk_variants:
        report += "## High Risk Variants\n\n"
        report += "The following variants have been identified as potentially significant and warrant discussion with a healthcare provider.\n\n"
        for variant in result.high_risk_variants:
            report += format_variant_detail(variant)

    # Moderate Risk Variants
    if result.moderate_risk_variants:
        report += "## Moderate Risk Variants\n\n"
        report += "These variants may have health implications depending on other factors.\n\n"
        for variant in result.moderate_risk_variants:
            report += format_variant_detail(variant)

    # Beneficial Variants
    if result.beneficial_variants:
        report += "## Beneficial Variants\n\n"
        report += "The following variants are associated with positive health outcomes.\n\n"
        for variant in result.beneficial_variants:
            report += format_variant_detail(variant)

    report += """
---

## Understanding This Report

### Risk Levels
- **High Risk**: Variants strongly associated with disease or requiring medical attention
- **Moderate Risk**: Variants with potential health implications
- **Low Risk**: Variants with minor or well-understood effects
- **Beneficial**: Variants associated with positive health outcomes

### Genotype Notation
- **Homozygous**: Two copies of the same allele (e.g., TT or CC)
- **Heterozygous**: One copy of each allele (e.g., TC)

---
*Generated by GeneHealth Analysis Platform*
"""
    return report


def generate_disease_risk_report(result: DiseaseRiskResult, subject_name: str) -> str:
    """Generate disease-focused risk report"""
    report = f"""# Disease Risk Assessment Report

**Subject:** {subject_name}
**Assessment Date:** {datetime.now().strftime("%B %d, %Y")}

---

## Executive Summary

Based on analysis of {result.total_variants_analyzed:,} genetic variants:
- **{len(result.high_risk_variants)}** variants associated with significantly elevated disease risk
- **{len(result.moderate_risk_variants)}** variants associated with moderately elevated risk
- **{result.clinvar_matches}** variants matched to the ClinVar clinical database

"""

    # Group by category
    categories_with_variants: Dict[str, List[VariantMatch]] = {}

    for variant in result.high_risk_variants + result.moderate_risk_variants:
        if variant.category not in categories_with_variants:
            categories_with_variants[variant.category] = []
        categories_with_variants[variant.category].append(variant)

    for category, variants in sorted(categories_with_variants.items()):
        report += f"## {category}\n\n"

        for variant in variants:
            risk_emoji = "🔴" if variant.risk_level == "high" else "🟡"
            report += f"### {risk_emoji} {variant.gene} - {variant.condition}\n\n"
            report += f"**Variant:** {variant.rsid} | **Genotype:** {variant.genotype}\n\n"
            report += f"{variant.description}\n\n"

            if variant.recommendations:
                report += "**Recommendations:**\n"
                for rec in variant.recommendations:
                    report += f"- {rec}\n"
                report += "\n"

            report += "---\n\n"

    report += """
## Important Notes

1. **Genetic risk is not destiny** - Many factors influence health outcomes including environment, lifestyle, and other genetic variants.

2. **Relative vs Absolute Risk** - A "2x increased risk" for a rare condition may still represent a very small absolute risk.

3. **Family History Matters** - Share this report with family members who may benefit from similar testing.

4. **Ongoing Research** - Our understanding of genetics continues to evolve. Regular re-analysis may reveal new insights.

---

## Disclaimer

This disease risk assessment is based on current scientific understanding and should not be used as a diagnostic tool. Risk predictions are probabilistic and cannot predict whether an individual will actually develop any condition. Always consult with qualified healthcare professionals for medical advice.

---
*Generated by GeneHealth Analysis Platform*
"""
    return report


def generate_protocol_report(result: DiseaseRiskResult, subject_name: str) -> str:
    """Generate actionable health protocol report"""
    report = f"""# Personalized Health Protocol

**Subject:** {subject_name}
**Generated:** {datetime.now().strftime("%B %d, %Y")}

---

## Overview

Based on your genetic analysis, this document outlines suggested health considerations and lifestyle modifications. These recommendations are general guidelines and should be discussed with your healthcare providers.

"""

    # Collect all recommendations
    all_recommendations: Dict[str, List[str]] = {}

    for variant in result.high_risk_variants + result.moderate_risk_variants:
        category = variant.category
        if category not in all_recommendations:
            all_recommendations[category] = []
        all_recommendations[category].extend(variant.recommendations)

    # Remove duplicates while preserving order
    for category in all_recommendations:
        seen = set()
        unique = []
        for rec in all_recommendations[category]:
            if rec not in seen:
                seen.add(rec)
                unique.append(rec)
        all_recommendations[category] = unique

    # Generate sections
    if "Drug Metabolism" in all_recommendations or result.pharmacogenomic_variants:
        report += "## Pharmacogenomics - Drug Response\n\n"
        report += "Your genetic variants may affect how you metabolize certain medications:\n\n"

        for variant in result.pharmacogenomic_variants:
            report += f"### {variant.gene}\n"
            report += f"- **Condition:** {variant.condition}\n"
            report += f"- **Genotype:** {variant.genotype}\n"
            for rec in variant.recommendations:
                report += f"- {rec}\n"
            report += "\n"

        report += "**Action Items:**\n"
        report += "- Share this information with all healthcare providers\n"
        report += "- Request pharmacogenomic review before starting new medications\n"
        report += "- Consider carrying a card with your drug metabolism status\n\n"

    if "Cardiovascular" in all_recommendations:
        report += "## Cardiovascular Health\n\n"
        for rec in all_recommendations["Cardiovascular"]:
            report += f"- {rec}\n"
        report += "\n"

    if "Metabolic" in all_recommendations:
        report += "## Metabolic Health\n\n"
        for rec in all_recommendations["Metabolic"]:
            report += f"- {rec}\n"
        report += "\n"

    if "Nutrition" in all_recommendations:
        report += "## Nutritional Considerations\n\n"
        for rec in all_recommendations["Nutrition"]:
            report += f"- {rec}\n"
        report += "\n"

    if "Detoxification" in all_recommendations:
        report += "## Detoxification Support\n\n"
        for rec in all_recommendations["Detoxification"]:
            report += f"- {rec}\n"
        report += "\n"

    if "Blood Clotting" in all_recommendations:
        report += "## Blood Clotting Considerations\n\n"
        report += "⚠️ **Important:** If you have variants affecting blood clotting, take extra precautions:\n\n"
        for rec in all_recommendations["Blood Clotting"]:
            report += f"- {rec}\n"
        report += "\n"

    report += """## General Wellness Recommendations

Based on your overall genetic profile:

### Testing & Monitoring
- Annual comprehensive metabolic panel
- Lipid panel every 6-12 months
- Vitamin D levels (especially if you have related variants)
- B12 and folate levels
- Inflammatory markers (CRP, homocysteine)

### Lifestyle
- Regular physical activity (150+ minutes moderate exercise weekly)
- Mediterranean-style diet rich in vegetables, healthy fats, and lean proteins
- Adequate sleep (7-9 hours nightly)
- Stress management practices

### Supplements to Discuss with Your Doctor
Based on your genetic variants, you may benefit from discussing:
- Methylated B vitamins (if MTHFR variants present)
- Vitamin D3 with K2 (if vitamin D metabolism variants)
- Omega-3 fatty acids
- CoQ10 (especially if taking statins)

---

## Follow-Up Actions

1. [ ] Schedule appointment to review results with healthcare provider
2. [ ] Update medication list with pharmacogenomic considerations
3. [ ] Implement applicable lifestyle recommendations
4. [ ] Consider genetic counseling for family planning if relevant
5. [ ] Set calendar reminder for annual re-analysis

---

## Disclaimer

This protocol is generated based on genetic analysis and current scientific literature. It is not a substitute for personalized medical advice. Individual responses to interventions vary, and any changes to medications, supplements, or lifestyle should be discussed with qualified healthcare providers.

---
*Generated by GeneHealth Analysis Platform*
"""
    return report


def format_variant_detail(variant: VariantMatch) -> str:
    """Format a single variant for the report"""
    text = f"### {variant.gene} - {variant.condition}\n\n"
    text += f"| Field | Value |\n"
    text += f"|-------|-------|\n"
    text += f"| rsID | {variant.rsid} |\n"
    text += f"| Genotype | {variant.genotype} |\n"
    text += f"| Category | {variant.category} |\n"
    text += f"| Risk Level | **{variant.risk_level.upper()}** |\n\n"
    text += f"{variant.description}\n\n"

    if variant.recommendations:
        text += "**Recommendations:**\n"
        for rec in variant.recommendations:
            text += f"- {rec}\n"
        text += "\n"

    text += "---\n\n"
    return text
